openapi: 3.0.1
info:
  title: Foccacia API
  description: An API for managing and acessing football teams and grouping them.
  version: 1.0.0
  contact:
    email: a51642@alunos.isel.pt 
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - description: Localhost server for testing API
    url: http://localhost:1904

security:
  - bearerAuth: []
tags:
  - name: Teams
  - name: Users
paths:
  /api/teams:
    description: Resource used for getting teams by name
    get:
      tags:
        - Teams
      summary: Get Teams
      description: By passing in the appropriate options, you can search for available Teams
      operationId: getTeamsByName
      parameters:
        - name: name
          in: query
          description: Name of the team
          required: true
          schema:
            type: string
            example: 'Sporting'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'
        '400':
          description: Invalid name supplied
        '404':
          description: Team not found
  /api/leagues:
    description: Resource used for getting leagues by team
    get:
      tags:
        - Leagues
      summary: Get Leagues
      description: By passing in the appropriate options, you can search for available Leagues
      operationId: getLeaguesByTeam
      parameters:
        - name: team
          in: query
          description: Id of the team
          required: true
          schema:
            type: integer
            minimum: 1
            example: 1
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/League'
        '400':
          description: Invalid team id supplied
        '404':
          description: League not found
  /api/groups:
    get:
      tags:
        - Groups
      summary: Get all Groups
      description: Get all groups of Teams
      operationId: getGroups
      security:
        - bearerAuth: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Group'
        '400':
          description: Invalid input

    post:
      tags:
        - Groups
      summary: Create Group
      description: Create a new group of Teams
      operationId: createGroup
      security:
        - bearerAuth: []
      requestBody:
        description: Group to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewGroup'
      responses:
        '201':
          description: Group created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewGroupCreated'
        '400':
          description: Invalid input
          
    put:
      tags:
        - Groups
      summary: Add Team to Group
      description: Add a Team to a Group
      operationId: addTeamToGroup
      security:
        - bearerAuth: []
      parameters:
        - name: groupId
          in: query
          description: Id of the group
          required: true
          schema:
            type: integer
            example: 1
        - name: teamId
          in: query
          description: Id of the team
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid input
        '404':
          description: Group not found
  /api/groups/{groupId}:
    delete:
      tags:
      - Groups
      summary: Delete Group by id
      description: Delete a Group
      operationId: deleteGroup
      parameters:
      - name: groupId
        in: path
        description: Id of the group
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Group deleted
        '400':
          description: Invalid input
        '404':
          description: Group not found
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    NewUser:
      type: object
      required:
        - username
      properties:
        username:
          type: string
          example: 'goncalo.pontes'
    NewUserCreated:
      type: object
      required:
        - token
      properties:
        token:
          type: string
          format: uuid
    User:
      type: object
      properties:
        id:
          type: integer
          example: 1
        username:
          type: string
          example: 'goncalo.pontes'
    League:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: 'Primeira Liga'
        type:
          type: string
          enum:
            - 'League'
            - 'Cup'
        logo:
          type: string
          example: 'https://media.api-sports.io/football/leagues/1.png'
    Venue:
      type: object
      properties:
        id:
          type: integer
          example: 556
        name:
          type: string
          example: 'Old Trafford'
        city:
          type: string
          example: 'Manchester'
        capacity:
          type: integer
          example: 76212
        surface:
          type: string
          example: 'grass'
        image:
          type: string
          example: 'https://media.api-sports.io/football/venues/556.png'
    Team:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: 'Sporting'
        country:
          type: string
          example: 'Portugal'
        code:
          type: string
          example: 'SCP'
        founded:
          type: integer
          minimum: 1000
          maximum: 9999
          example: 1906
        national:
          type: boolean
          example: true
        logo:
          type: string
          example: 'https://upload.wikimedia.org/wikipedia/pt/thumb/3/3e/Sporting_Clube_de_Portugal.png/180px-Sporting_Clube_de_Portugal.png'
    NewGroup:
      type: object
      required:
        - name
        - description
      properties:
        name:
          type: string
          example: 'Group A'
        description:
          type: string
          example: 'Group A of the Champions League'
    NewGroupCreated:
      type: object
      required:
        - id
        - ownerId
      properties:
        id:
          type: integer
          example: 1
        ownerId:
          type: integer
          example: 1
    Group:
      allOf:
        - type: object
        - $ref: '#/components/schemas/NewGroup'
          required:
            - id
            - ownerId
          properties:
            id:
              type: integer
              example: 1
            ownerId:
              type: integer
              example: 1
